### ISSUE TITLE
Add assertIsNumber()

### ISSUE THREAD

**Issue by SpacePossum** [GeckoPackages/GeckoPHPUnit#10]
PHPUnit does not have a negative test for its `assertNan()`.

**Comment by keradus** [comment]
There is `assertNan` since 5.0.
So again, question is should this library provides polyfills or not (#21)

**Comment by SpacePossum** [comment]
Indeed, this one can be dropped.
I like the idea of polyfills for PHPUnit, I'll think about it some more.
