### ISSUE TITLE
polyfill trait

### ISSUE THREAD

**Issue by keradus** [GeckoPackages/GeckoPHPUnit#21]
from other PR:
> I have some other ideas as well, and besides; one the asserts in this package (`isDirectory`) has been added to PHPUnit itself so I've to see what I do with that.

I was thinking about this as well (just with different methods, but in the end it doesn't matter).
What do you think about creating compatibility trait, that will provide assertions that are not yet available in PHPUnit that the user is using?

Nice thing is that if we use the trait he will have the assertion from either Gecko trait or native PHPUnit implementation. (trait import will still work if one is using newest PHPUnit and assertion will be called with original implementation, not the one from trait)

**Comment by SpacePossum** [comment]
I've to be realistic here; I won't have the time to work on a polyfill trait/layer for PHPUnit.
Secondly it would probably better to have such a polyfill in a whole new project.
