### ISSUE TITLE
scalar asserts should be reworked

### ISSUE THREAD

**Issue by keradus** [GeckoPackages/GeckoPHPUnit#22]
IMO `scalar asserts` should be removed, in fact methods like `assertString`, `assertFloat` and so one shoul be removed.
Why ? PHPUnit natively has `assertInternalType` assertion, which is basically the same (just combined into one method, which is more generic).
I think that there shouldn't be any assertion that duplicates already existing functionality just with different name.

On the other side, there could be a polyfill (see #21) for `assertInternalType` if one is using PHPUnit < 4.4

**Comment by SpacePossum** [comment]
I've removed all non-type asserts from the trait for the 2.x line, so this could indeed be done there. There we can also start adding polyfills :)

**Comment by keradus** [comment]
I was thinking about that polyfills for a while as well and checked background for it.
Maybe it would be nice to make a dedicated polyfill package, to distinguish extra functionality from polyfilling one ?
Like there is symfony/polyfill

**Comment by pthreat** [comment]
Arrays are not scalar thus do not belong into the ScalarTrait 

http://php.net/manual/en/function.is-scalar.php

" Types array, object and resource are not scalar. "

**Comment by SpacePossum** [comment]
@pthreat you're absolutely right. Looking back on the design of the `ScalarAssertTrait` I agree it was named wrong. I'll make a note to refactor for 3.x, thanks :+1:

**Comment by SpacePossum** [comment]
with https://github.com/GeckoPackages/GeckoPHPUnit/pull/36 merged I think there is not much left here to do, but feel free all to comment with ideas and feedback!

**Comment by SpacePossum** [comment]
Closing as the wrongly named `assert` method have been moved to an `alias` trait, one can use if wanted or ignore if not.
Thanks for the insights, it was a nice clean up :)

PS.
on polyfill, I would like such a package but I think it would be best to have it in a dedicated repo, this one has the scope of adding functionality (so might drop functionality if PHPUnit adds something similar)

**Comment by keradus** [comment]
:+1:
thanks

---------------

after some time, I'm :-1: for polyfilling, I rather go in direction to phpunit upgrade so no polyfill needed
