### ISSUE TITLE
PHPUnit 6

### ISSUE THREAD

**Issue by GrahamCampbell** [GeckoPackages/GeckoPHPUnit#33]
Is PHPUnit 6 support planned? If so, is there anything I can do to help?

**Comment by SpacePossum** [comment]
it is planned, together with a bump to PHP7 (of course). New version will have a bunch of stuff removed.
I'll hope to work on this the upcoming 3 weeks (on and of) or so.

**Comment by GrahamCampbell** [comment]
Cool. :+1:

**Comment by SpacePossum** [comment]
master has been made compat with PHPUnit 6, feel free to test :)

**Comment by TomasVotruba** [comment]
@SpacePossum Great job!

**Comment by SpacePossum** [comment]
closing as https://github.com/GeckoPackages/GeckoPHPUnit/pull/35 is merged and will be part of the next major release (3.0)

**Comment by TomasVotruba** [comment]
Thanks for update
