### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by remicollet** [GeckoPackages/GeckoPHPUnit#38]
Nothing on https://github.com/GeckoPackages/GeckoPHPUnit/releases/tag/v2.1

At least should have info about c565b8e3e262e1c86ee4e265987edab963b9aec0

having to dig in git history is not funny ;)

BTW could be nice to have a "real" changelog
http://keepachangelog.com/

**Comment by SpacePossum** [comment]
Hi!

Thanks for raising this issue; it's fair point :+1:
TBH I never got around figuring out how to do the release notes in a proper way. I'll see if can make one after the fact for 2.1 ;)

Did the 2.1 release break anything for you?

**Comment by remicollet** [comment]
> Did the 2.1 release break anything for you?
No

BTW, I not a real user, only downstream packager, and this package is used by some projects (e.g. php-cs-fixer) during their test suite.

So I need the changelog to give this information to our users
ex: https://bodhi.fedoraproject.org/updates/FEDORA-2017-930b767432

And FYI everything is monitored, ex:
https://apps.fedoraproject.org/koschei/package/php-cs-fixer?collection=f27
(laste build raised by php-gecko-packages-gecko-php-unit update)

More info about Koschei
https://blog.remirepo.net/post/2014/08/12/Koschei-continuous-integration-of-PHP-stack-in-Fedora
