### ISSUE TITLE
PHPUnit incompatibility

### ISSUE THREAD

**Issue by keradus** [GeckoPackages/GeckoPHPUnit#51]
GeckoPHPUnit 3.0 must have conflict with PHPUnit < 6.0, as it relies on 6.0 classes
similar, GeckoPHPUnit 2.x must have conflict with PHPUnit 6.

or better, as GeckoPHPUnit relies on PHPUnit classes, PHPUnit shall be added as (non-dev) dependency.

**Comment by keradus** [comment]
effect is that I'm able to install PHPUnit 6 with GeckoPHPUnit 2, which leads to crash

**Comment by SpacePossum** [comment]
I left PHPUnit out as requirement as I didn't want to force users to install through composer,
having the conflicts set in `composer.json` makes sense to be me. I'll prepare PR's soon I hope. Thanks for reporting!

**Comment by keradus** [comment]
reasoning makes sense :+1:

thanks !

**Comment by keradus** [comment]
keep in mind, that if I have: (in composer-like notation):
```json
{
    "PHPUnit": "^6.0",
    "GeckoPHPUnit": "^2.2"
}
```

It is crashing due to incompatibilities
If you will add conflict key and release it under 2.2.1, then composer will refuse to install 2.2.1 due to incompatibility with PHPUnit 6.0 and it will install 2.2.0 instead, leaving me with ~hidden conflict and crash during execution anyway

**Comment by SpacePossum** [comment]
conflicts have added to v2, v3 and master branches,
thanks for reporting!

**Comment by garak** [comment]
Is there any plan for phpunit 7 compatibility?

**Comment by SpacePossum** [comment]
I think a better roadmap would be to take whatever one finds useful here and PR to PHPUnit directly, so in the end this package can go.

**Comment by garak** [comment]
Meanwhile, I think you should remove phpunit 7 mention from README (and, instead, outline current incompatibility)

**Comment by SpacePossum** [comment]
> remove phpunit 7 mention from README

I think it is not there?

```
Requirements
PHP 7
PHPUnit 6
```

**Comment by garak** [comment]
My bad, miread "PHP 7" as "PHPUnit 7". Never mind.
